# Source: https://github.dev/IBM/actions-ibmcloud-iks

name: Build and deploy to IBM Kubernetes

on:
  push:
    branches:
      - release/part1

env:
  GITHUB_SHA: ${{ github.sha }}
  IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
  IBM_CLOUD_REGION: eu-de
  K8S_NAMESPACE: part1
  IMAGE_NAME: se-currency-converter-part1 # ADAPT!
  IKS_CLUSTER: cgbisc9f0brfqd97s8d0 # name or id of cluster
  DEPLOYMENT_NAME: se-currency-converter-part1 # ADAPT!
  INTERNAL_PORT: 8000 # ADAPT!
  EXTERNAL_PORT: 32767 # ADAPT!
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Download and Install IBM Cloud CLI
      - name: Install IBM Cloud CLI
        run: |
          curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
          ibmcloud login --apikey "${IBM_CLOUD_API_KEY}" -r "${IBM_CLOUD_REGION}" -g Default
          ibmcloud --version
          ibmcloud api https://cloud.ibm.com
          ibmcloud config --check-version=false
          ibmcloud plugin install -f kubernetes-service
      # Build the Docker image
      - name: Build with Docker
        run: |
          docker build -t "$DOCKER_USER"/"$IMAGE_NAME":"$GITHUB_SHA" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" .
      # Deploy the Docker image to the IKS cluster
      - name: Deploy to IKS
      # Change the service type to the actual service
        run: |
          ibmcloud login --apikey "${IBM_CLOUD_API_KEY}" -r "${IBM_CLOUD_REGION}" -g Default
          ibmcloud ks cluster config --cluster $IKS_CLUSTER
          kubectl create namespace $K8S_NAMESPACE --dry-run=client -o yaml > namespace.yaml
          kubectl apply -f namespace.yaml
          kubectl config set-context --current --namespace=$K8S_NAMESPACE
          kubectl create deployment $DEPLOYMENT_NAME --image="$DOCKER_USER"/"$IMAGE_NAME":"$GITHUB_SHA" --dry-run -o yaml > deployment.yaml
          kubectl apply -f deployment.yaml
          kubectl rollout status deployment/$DEPLOYMENT_NAME
          kubectl create service nodeport $DEPLOYMENT_NAME --tcp=$EXTERNAL_PORT:$INTERNAL_PORT --node-port=$EXTERNAL_PORT --dry-run -o yaml > service.yaml
          kubectl apply -f service.yaml
          kubectl get services -o wide